# Generated by Django 4.1.2 on 2022-11-04 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='room_name',
            new_name='group',
        ),
    ]
