# Generated by Django 4.1.2 on 2022-11-04 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_room_name_messages_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='username',
            new_name='user',
        ),
    ]
